name: nimbbl_flutter_sample_app
description: "Nimbbl Flutter SDK Sample App - Demonstrates payment integration with web and mobile support"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+18

environment:
  sdk: '>=2.12.0 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  dio: ^5.8.0+1
  dotted_line: ^3.2.3
  dotted_border: ^2.0.0
  dropdown_button2: ^2.3.9
  email_validator: ^3.0.0
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  intl: ^0.19.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.2
  talker_dio_logger: ^4.6.11
  url_launcher: ^6.3.1
  fluttertoast: ^8.2.12
  win32: ^5.10.1

  cupertino_icons: ^1.0.8
  
  # Nimbbl Flutter WebView SDK
  # Using published alpha version
  nimbbl_mobile_kit_flutter_webview_sdk: ^1.1.1-alpha.2
  
  # Local SDK (commented out - using published version)
  # nimbbl_mobile_kit_flutter_webview_sdk:
  #   path: /Users/sandeepyadav/Documents/nimbbl_bitbucket_repos/nimbbl_mobile_kit_flutter_webview_sdk
  
  # Firebase dependencies (optional - can be disabled in AppConstants)
  firebase_crashlytics: ^5.0.4
  firebase_analytics: ^12.0.4
  firebase_core: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - assets/icons/
     - assets/
     - assets/fonts/

  # Custom fonts - Gordita (matching React implementation)
  fonts:
    - family: Gordita
      fonts:
        - asset: assets/fonts/Gordita-Light.ttf
          weight: 300
        - asset: assets/fonts/Gordita-Regular.ttf
          weight: 400
        - asset: assets/fonts/Gordita-Medium.otf
          weight: 500  # Medium weight (matching React font-[Gordita-medium])
        - asset: assets/fonts/Gordita-Bold.ttf
          weight: 700
